"""The site, asserted against a real build of the real pack.

Unlike the other test modules, most of these tests build the actual site rather than a
miniature one. That is deliberate and it is the point of several of them: the failures
this work package is guarding against — a wide table that overflows a phone, a raw
markdown file Jekyll ate, a hard-coded hostname, `/AGENTS.md` being subtly wrong while
the site looks perfect — are all failures that only exist in the built output, against
the real content. A sample page would prove nothing about the tables in
`storytelling.md`.

The one thing to know before adding a test here: `mkdocs.config.load_config` takes
overrides, so a test can build the real site with a different `site_url` without writing
a second config or touching the repo. That is what makes the base-swap assertion (C3,
NFR-001, SC-006) a real test rather than a grep.
"""

from __future__ import annotations

import importlib.util
import re
import subprocess
from pathlib import Path
from typing import Any, Final, Iterator

import pytest
import yaml
from mkdocs.commands.build import build as mkdocs_build
from mkdocs.config import load_config as mkdocs_load_config
from mkdocs.exceptions import Abort

from build.config import BuildConfig, load_config
from build.rename import PUBLISHED_NAME, SOURCE_NAME
from build.roles import load_documents
from build.site import (
    NOJEKYLL_FILENAME,
    PDF_FILENAME,
    PITCH_MARKER,
    PITCH_SOURCE,
    SiteError,
    extract_pitch,
)

_REPO_ROOT: Final[Path] = Path(__file__).resolve().parents[1]
_MKDOCS_YML: Final[Path] = _REPO_ROOT / "mkdocs.yml"

#: A second base, deliberately unlike the first in every respect that matters: another
#: host, another subpath depth, and the custom-domain case (SC-006's actual scenario).
_OTHER_BASE: Final[str] = "https://guide.example.test/"

#: Text files in the output whose content is generated by us or by MkDocs. The raw `.md`
#: files are excluded from some scans because they are the pack's own bytes.
_TEXT_SUFFIXES: Final[tuple[str, ...]] = (".html", ".xml", ".json", ".txt", ".css", ".md")


def _build(site_dir: Path, *, site_url: str | None = None) -> None:
    """Build the real site into ``site_dir``, optionally with a different base."""
    overrides: dict[str, Any] = {"site_dir": str(site_dir)}
    if site_url is not None:
        overrides["site_url"] = site_url
    config = mkdocs_load_config(config_file=str(_MKDOCS_YML), strict=True, **overrides)
    mkdocs_build(config)


def _text_files(site_dir: Path, *, suffixes: tuple[str, ...] = _TEXT_SUFFIXES) -> Iterator[Path]:
    for path in sorted(site_dir.rglob("*")):
        if path.is_file() and path.suffix in suffixes:
            yield path


@pytest.fixture(scope="session")
def site(tmp_path_factory: pytest.TempPathFactory) -> Path:
    """The real site, built once with the configured base."""
    site_dir = tmp_path_factory.mktemp("site")
    _build(site_dir)
    return site_dir


@pytest.fixture(scope="session")
def swapped_site(tmp_path_factory: pytest.TempPathFactory) -> Path:
    """The real site, built with a different base and nothing else changed."""
    site_dir = tmp_path_factory.mktemp("site-swapped")
    _build(site_dir, site_url=_OTHER_BASE)
    return site_dir


@pytest.fixture(scope="session")
def config() -> BuildConfig:
    return load_config(_MKDOCS_YML)


# --------------------------------------------------------------------------------------
# T013 — the landing page is derived, and fails loudly when it cannot be
# --------------------------------------------------------------------------------------

_PITCH_FIXTURE = (
    "# The Kit\n"
    "\n"
    "**What is this?** In a sentence: the thing.\n"
    "\n"
    "A second paragraph of pitch.\n"
    "\n"
    "---\n"
    "\n"
    "*Hand this to an LLM.*\n"
    "\n"
    "## 0. The mission\n"
    "\n"
    "Not the pitch.\n"
)


def test_the_pitch_is_extracted_verbatim() -> None:
    """The landing page is the kit's words, not a paraphrase of them (FR-001, NFR-003)."""
    pitch = extract_pitch(_PITCH_FIXTURE)
    assert pitch.startswith("**What is this?** In a sentence: the thing.")
    assert "A second paragraph of pitch." in pitch


def test_the_pitch_stops_at_the_thematic_break() -> None:
    """The section ends where the kit ends it — the rule below the opening."""
    pitch = extract_pitch(_PITCH_FIXTURE)
    assert "Hand this to an LLM" not in pitch
    assert "Not the pitch" not in pitch


def test_the_pitch_stops_at_the_next_heading() -> None:
    """A kit that loses its horizontal rule still yields a pitch, not the whole document."""
    pitch = extract_pitch("**What is this?** The thing.\n\n## 0. The mission\n\nNo.\n")
    assert pitch == "**What is this?** The thing."


def test_a_missing_pitch_fails_the_build_rather_than_publishing_an_empty_page() -> None:
    """The loud failure T013 asks for.

    A silent one would publish a blank front door, or — worse — invite someone to author
    a landing page by hand, which is the drift NFR-003 exists to prevent.
    """
    with pytest.raises(SiteError) as raised:
        extract_pitch("# The Kit\n\nNo pitch here at all.\n")
    assert PITCH_MARKER in str(raised.value)
    assert PITCH_SOURCE in str(raised.value)


def test_an_empty_pitch_fails_the_build() -> None:
    with pytest.raises(SiteError):
        extract_pitch("# The Kit\n\n**What is this?**\n\n---\n\n## Next\n")


def test_the_real_kit_still_carries_the_pitch_the_landing_page_needs(config: BuildConfig) -> None:
    """The extraction is only as good as its grip on the real document.

    If someone rewords the kit's opening, this fires here — where the message explains
    what to do — rather than in a mysteriously blank site.
    """
    source = (config.pack_dir / PITCH_SOURCE).read_text(encoding="utf-8")
    assert extract_pitch(source).startswith(PITCH_MARKER)


def _longest_plain_run(markdown: str) -> str:
    """The longest run of unformatted words in some markdown.

    Derived rather than hard-coded, so that this test keeps working when the kit's
    wording changes — which it will, and which is the entire reason the landing page is
    extracted rather than authored. A run with no markdown syntax and no line break in it
    survives rendering unchanged, so it can be looked for in the HTML.
    """
    runs: list[str] = re.findall(r"[A-Za-z][A-Za-z ,';]{30,}", markdown)
    assert runs, "no plain-text run to look for"
    return max(runs, key=len).strip()


def test_the_landing_page_is_the_kits_pitch(site: Path, config: BuildConfig) -> None:
    """FR-001: the first thing a human reads is the guide's own pitch, not a directory."""
    index = (site / "index.html").read_text(encoding="utf-8")
    source = (config.pack_dir / PITCH_SOURCE).read_text(encoding="utf-8")
    pitch = extract_pitch(source)

    assert _longest_plain_run(pitch) in index

    # ...and the pitch only. The landing page is the front door, not the whole kit.
    assert "## 0. The mission" not in index
    assert _longest_plain_run(source.split("## 0. The mission", 1)[1]) not in index


def test_the_landing_page_links_the_pdf_prominently(site: Path, config: BuildConfig) -> None:
    """FR-004: WP04 produces the book; the landing page is where a reader looks for it."""
    index = (site / "index.html").read_text(encoding="utf-8")
    assert config.absolute_url(PDF_FILENAME) in index


def test_the_landing_page_points_a_model_at_the_bootstrap(site: Path, config: BuildConfig) -> None:
    """FR-008: the one address to hand a model is on the front page, in words."""
    index = (site / "index.html").read_text(encoding="utf-8")
    assert config.absolute_url(PUBLISHED_NAME) in index


def test_the_readme_is_an_ordinary_page_and_not_the_index(site: Path) -> None:
    """The collision that fails silently, and would have shipped.

    MkDocs maps `README.md` to `index.html` exactly as it maps `index.md` — so the pack's
    README lands on the address the derived landing page occupies, both render, one
    overwrites the other, and the build exits 0 under `--strict` with no warning. Its own
    conflict detection does not see it: that compares the files it walked out of
    `docs_dir`, and the landing page is generated after that.

    The contract is explicit — README.md is the pack branch's front door, not the site
    index, and it publishes as an ordinary page (roles-declaration § The landing page).
    So: the root is the pitch, and the README is somewhere else, intact.
    """
    index = (site / "index.html").read_text(encoding="utf-8")
    assert PITCH_MARKER.strip("*") in index or "What is this?" in index

    readme = site / "README" / "index.html"
    assert readme.is_file(), (
        "README.md does not publish as a page. It has almost certainly collided with the "
        "generated landing page at index.html — silently, because MkDocs renders both."
    )
    assert "The documents" in readme.read_text(encoding="utf-8")


def test_the_landing_page_is_not_authored_into_the_pack(config: BuildConfig) -> None:
    """C-002/C-006: derivation is the whole point. An index.md in the pack is the failure."""
    assert not (config.pack_dir / "index.md").exists(), (
        "src/pack/index.md exists. The landing page is derived from the kit's pitch at "
        "build time; an authored one is hand-written published content (NFR-003) and "
        "will drift from the kit the first time the pitch is reworded."
    )


# --------------------------------------------------------------------------------------
# T012/T014 — nav, search, and the per-page AI pointer
# --------------------------------------------------------------------------------------


def test_the_nav_is_the_declared_reading_order(site: Path, config: BuildConfig) -> None:
    """FR-001: the site's order is the declaration's order, derived and never re-typed."""
    index = (site / "index.html").read_text(encoding="utf-8")
    links = re.findall(r'<a href="([^"]+)" class="md-nav__link"', index)

    declared = [Path(name).stem for name in config.nav]
    rendered = [link.strip("./").split("/")[0] for link in links if link not in {".", "./"}]
    # The nav also carries the two not_in_book documents' pages; the assertion is that
    # the chapters appear, in order, among them.
    ordered = [stem for stem in rendered if stem in declared]
    assert ordered == declared


def test_search_is_built(site: Path) -> None:
    """FR-001 requires the site be searchable; MkDocs' index is how."""
    assert (site / "search" / "search_index.json").is_file()


def test_every_page_carries_a_visible_ai_pointer(site: Path) -> None:
    """FR-002, the human half: a reader who wants the clean source can see the link."""
    pages = [p for p in site.rglob("index.html")]
    assert len(pages) > 10, "sanity: the real site has a page per document"
    for page in pages:
        html = page.read_text(encoding="utf-8")
        assert "Reading this as an AI?" in html, f"{page} carries no visible AI pointer"


def test_every_page_declares_its_markdown_alternate(site: Path, config: BuildConfig) -> None:
    """FR-002, the machine half: for a model that never renders the page."""
    documents = load_documents(config.pack_dir, config)
    for document in documents:
        page = site / Path(document.filename).stem / "index.html"
        html = page.read_text(encoding="utf-8")
        expected = config.absolute_url(document.published_name)
        assert (
            f'<link rel="alternate" type="text/markdown" href="{expected}">' in html
        ), f"{page} does not declare {expected} as its markdown alternate"


def test_the_bootstraps_page_points_at_agents_md(site: Path, config: BuildConfig) -> None:
    """FR-010: the pointer uses `Document.published_name`, so it says AGENTS.md.

    A pointer at `start.md` would 404 — the site publishes the bootstrap under its
    published name only. This is the case that is invisible on a site that otherwise
    looks perfect.
    """
    html = (site / Path(SOURCE_NAME).stem / "index.html").read_text(encoding="utf-8")
    assert config.absolute_url(PUBLISHED_NAME) in html
    assert config.absolute_url(SOURCE_NAME) not in html


# --------------------------------------------------------------------------------------
# T015 — the raw markdown surface. The mission's reason for existing.
# --------------------------------------------------------------------------------------


def test_agents_md_exists_and_is_the_bootstrap(site: Path, config: BuildConfig) -> None:
    """FR-008: `{base}AGENTS.md` is the one URL a creator hands to an LLM."""
    published = site / PUBLISHED_NAME
    assert published.is_file(), "the site publishes no AGENTS.md; the mission's one URL 404s"

    source = (config.pack_dir / SOURCE_NAME).read_text(encoding="utf-8")
    text = published.read_text(encoding="utf-8")
    assert text.startswith(source.splitlines()[0])
    assert "the brief for an LLM" in text


def test_every_document_is_published_as_raw_markdown(site: Path, config: BuildConfig) -> None:
    """FR-007: raw markdown at parallel paths, for every document."""
    for document in load_documents(config.pack_dir, config):
        assert (
            site / document.published_name
        ).is_file(), f"{config.absolute_url(document.published_name)} would 404"


def test_the_raw_markdown_is_byte_identical_to_the_pack(site: Path, config: BuildConfig) -> None:
    """FR-007: byte-identical — the one exception being the rename FR-010 forces.

    Every document that does not mention the bootstrap must come out of the build
    unchanged, to the byte. If this fails, something in the build is editing the product
    (C-002).
    """
    checked = 0
    for document in load_documents(config.pack_dir, config):
        original = (config.pack_dir / document.filename).read_bytes()
        if SOURCE_NAME.encode() in original:
            continue  # covered by the rewrite tests below
        assert (
            site / document.published_name
        ).read_bytes() == original, f"{document.published_name} was altered on its way to the site"
        checked += 1
    assert checked > 5, "sanity: most documents do not mention the bootstrap"


def test_no_published_document_still_points_at_start_md(site: Path) -> None:
    """FR-010: a model that fetched AGENTS.md and followed a link would otherwise 404."""
    offenders = []
    for path in site.glob("*.md"):
        text = path.read_text(encoding="utf-8")
        if re.search(r"(?<![\w\-])start\.md(?!\w)(?!\.\w)", text):
            offenders.append(path.name)
    assert (
        not offenders
    ), f"{offenders} still reference start.md, which is not published under that name"


def test_the_rewrite_did_not_maul_getting_started(site: Path) -> None:
    """THE trap `build.rename` exists for, asserted on the real published bytes.

    `sed s/start.md/AGENTS.md/g` turns `getting-started.md` into `getting-AGENTS.md` —
    a broken link no other test here would notice, because the file it breaks still
    exists and the page it breaks still renders.
    """
    for path in site.glob("*.md"):
        text = path.read_text(encoding="utf-8")
        assert "getting-AGENTS.md" not in text, f"{path.name} was corrupted by the rewrite"
    assert (site / "getting-started.md").is_file()


def test_the_bootstrap_is_published_only_under_its_published_name(site: Path) -> None:
    """One bootstrap, one address. `start.md` is the name on `main`, not on the web."""
    assert not (site / SOURCE_NAME).exists(), (
        "the site publishes start.md as well as AGENTS.md — two addresses for the "
        "bootstrap is exactly the drift FR-010's rename exists to end"
    )


# --------------------------------------------------------------------------------------
# T016 — .nojekyll, subpath correctness, the base swap, and link validation
# --------------------------------------------------------------------------------------


def test_nojekyll_is_emitted(site: Path) -> None:
    """FR-012: without it, Jekyll processes the output and can eat the raw markdown."""
    marker = site / NOJEKYLL_FILENAME
    assert marker.is_file()
    assert marker.read_bytes() == b""


def test_no_link_discards_the_subpath(site: Path, config: BuildConfig) -> None:
    """C-003/C2: the site is served from a subpath; `/AGENTS.md` 404s there.

    Note what this does NOT ban. MkDocs renders `404.html` with root-relative URLs on
    purpose — a 404 can be served in place of any path, so it cannot use relative ones —
    and those URLs are correct precisely because they carry the subpath. The failure is a
    root-relative link that DROPS the subpath, so that is what is asserted.
    """
    subpath = "/" + config.base_url.split("//", 1)[1].split("/", 1)[1]
    assert subpath == "/dungeon-masters-guide/", "sanity: the configured base is a subpath"

    offenders: list[str] = []
    for path in _text_files(site, suffixes=(".html",)):
        for match in re.finditer(r'(?:href|src)="(/[^/"][^"]*)"', path.read_text(encoding="utf-8")):
            if not match.group(1).startswith(subpath):
                offenders.append(f"{path.relative_to(site)}: {match.group(1)}")
    assert not offenders, "root-relative links that drop the subpath will 404:\n" + "\n".join(
        offenders
    )


def test_no_module_hard_codes_the_deployed_host() -> None:
    """NFR-001, at the source rather than the output: the base is configuration.

    `build/config.py` is the one place the default may appear, because it is the place
    that declares it.
    """
    host = "conspiracy-larp.github.io"
    offenders = [
        path.name
        for path in (_REPO_ROOT / "src" / "build").glob("*.py")
        if path.name != "config.py" and host in path.read_text(encoding="utf-8")
    ]
    assert not offenders, f"{offenders} hard-code the deployed host instead of using absolute_url()"


def test_the_theme_hard_codes_no_host() -> None:
    """The same rule, one layer out: a template is just as capable of welding a hostname in."""
    host = "conspiracy-larp.github.io"
    for path in (_REPO_ROOT / "src" / "theme").rglob("*"):
        if path.is_file():
            assert host not in path.read_text(encoding="utf-8"), f"{path} hard-codes the host"


def test_swapping_the_base_moves_every_generated_address(
    site: Path, swapped_site: Path, config: BuildConfig
) -> None:
    """C3/NFR-001/SC-006: one base, one edit — asserted by building the site twice.

    This is the test that catches a hard-coded hostname surviving in the site while
    `llms.txt` is clean. Without it, NFR-001 holds for the machine files and is merely
    hoped for here — and the site is where the addresses are most numerous: the AI
    pointer, the markdown alternate, the PDF link, the sitemap.

    The pack itself contains no absolute address of the guide (asserted below), so every
    occurrence of the base in the output is one the build generated. That is what lets
    this assertion be a clean "none survives" rather than a list of exceptions.
    """
    original_base = config.base_url

    # The bootstrap and the human on-ramp quote the base deliberately — they must print an
    # address a cold model or a person can act on (BOOTSTRAP_MAY_QUOTE_THE_BASE). Their raw
    # copies, rendered pages and the search index that carries their text survive by design.
    # Everything else must follow the configured base.
    def _is_declared_exception(rel: str) -> bool:
        name = Path(rel).name
        return name in {"AGENTS.md", "getting-started.md", "start.md"} or rel.startswith(
            ("getting-started/", "start/", "search/")
        )

    survivors = [
        str(path.relative_to(swapped_site))
        for path in _text_files(swapped_site)
        if original_base in path.read_text(encoding="utf-8", errors="ignore")
        and not _is_declared_exception(str(path.relative_to(swapped_site)))
    ]
    assert not survivors, (
        f"after rebuilding with {_OTHER_BASE}, these files still contain {original_base}: "
        f"{survivors}. Something composed an address from a literal rather than from the "
        "configured base — moving the guide to a custom domain would half-work (SC-006)."
    )

    followed = {
        str(path.relative_to(swapped_site))
        for path in _text_files(swapped_site)
        if _OTHER_BASE in path.read_text(encoding="utf-8", errors="ignore")
    }
    generated = {
        str(path.relative_to(site))
        for path in _text_files(site)
        if original_base in path.read_text(encoding="utf-8", errors="ignore")
    }
    assert generated, "sanity: the site generates absolute addresses at all"
    assert followed == generated, (
        "the files carrying an absolute address changed when the base did: "
        f"{followed ^ generated}"
    )


#: The only two documents allowed to quote the deployed address, and why.
#:
#: The bootstrap's whole job is to be fetched cold by a model that has nothing else: it
#: cannot derive an address it was not given. `getting-started.md` must print a URL a human
#: can paste. Neither can be expressed relatively, so this is a real exception, taken
#: deliberately on 2026-07-17 rather than discovered later.
#:
#: The cost is stated plainly: changing the base is a one-value change **plus these two
#: prose edits** (url-map's Amendment rule). SC-006's promise holds for every generated
#: address; it does not hold for the two the guide speaks aloud.
#:
#: The allow-list is the point. A *third* document quoting the base still fails here.
BOOTSTRAP_MAY_QUOTE_THE_BASE: Final[frozenset[str]] = frozenset({"start.md", "getting-started.md"})


def test_only_the_bootstrap_quotes_an_absolute_address_of_itself(
    config: BuildConfig,
) -> None:
    """The premise the swap test rests on, pinned down rather than assumed.

    If any *other* document quotes the deployed base, the swap above stops being a build
    question and becomes a content one (url-map's Amendment rule) — and this test is where
    that is discovered.
    """
    quoting = {
        path.name
        for path in config.pack_dir.glob("*.md")
        if "conspiracy-larp.github.io" in path.read_text(encoding="utf-8")
    }
    unexpected = sorted(quoting - BOOTSTRAP_MAY_QUOTE_THE_BASE)
    assert not unexpected, (
        f"{unexpected} quote the deployed base. Only the bootstrap may: it is fetched cold "
        "and cannot derive an address. Changing the base is then a content change too "
        "(C-006, url-map Amendment rule) — escalate rather than editing the pack."
    )


def test_the_ai_pointer_follows_the_base(swapped_site: Path) -> None:
    """The addresses C3 names, specifically, on the swapped build."""
    html = (swapped_site / "ethics" / "index.html").read_text(encoding="utf-8")
    assert f'<link rel="alternate" type="text/markdown" href="{_OTHER_BASE}ethics.md">' in html

    index = (swapped_site / "index.html").read_text(encoding="utf-8")
    assert f"{_OTHER_BASE}{PDF_FILENAME}" in index
    assert f"{_OTHER_BASE}{PUBLISHED_NAME}" in index


def test_the_swapped_site_still_publishes_the_machine_surface(swapped_site: Path) -> None:
    """The base moves; the shape of the contract does not."""
    assert (swapped_site / PUBLISHED_NAME).is_file()
    assert (swapped_site / NOJEKYLL_FILENAME).is_file()


# --- Link validation (C2, FR-013) ------------------------------------------------------


def _validation_declaration() -> dict[str, Any]:
    """The `validation:` block from the real mkdocs.yml.

    Read from the config rather than restated, so these tests fail if the settings are
    weakened — which is the only way they could stop being true.
    """
    raw = yaml.safe_load(_MKDOCS_YML.read_text(encoding="utf-8").split("theme:", 1)[0])
    validation = raw["validation"]
    assert isinstance(validation, dict)
    return validation


def _synthetic_project(tmp_path: Path, body: str, *, validation: dict[str, Any] | None) -> Path:
    """A minimal project with one broken link, built with our validation settings."""
    docs = tmp_path / "docs"
    docs.mkdir()
    (docs / "index.md").write_text("# Home\n\n## A real anchor\n\n" + body, encoding="utf-8")

    config: dict[str, Any] = {
        "site_name": "Probe",
        "site_url": "https://example.test/probe/",
        "docs_dir": "docs",
        "site_dir": str(tmp_path / "site"),
        "nav": [{"Home": "index.md"}],
    }
    if validation is not None:
        config["validation"] = validation

    path = tmp_path / "mkdocs.yml"
    path.write_text(yaml.safe_dump(config, sort_keys=False), encoding="utf-8")
    return path


def _build_probe(config_path: Path) -> None:
    mkdocs_build(mkdocs_load_config(config_file=str(config_path), strict=True))


@pytest.mark.parametrize(
    ("body", "kind"),
    [
        ("[gone](no-such-document.md)\n", "a link to a document that does not exist"),
        ("[anchor](index.md#not-a-real-anchor)\n", "a link to an anchor that does not exist"),
        ("[odd](some/directory/)\n", "a link that cannot be an internal document"),
    ],
)
def test_a_broken_internal_link_fails_a_strict_build(tmp_path: Path, body: str, kind: str) -> None:
    """FR-013 on the site — the last published surface that was not covered (C2).

    Cross-references must resolve on *every* published surface. WP07 covers the two
    branches and WP04 covers the book's flattened references; this closes the site, by
    making MkDocs' own link validation loud enough for `--strict` to act on.
    """
    config_path = _synthetic_project(tmp_path, body, validation=_validation_declaration())
    with pytest.raises(Abort):
        _build_probe(config_path)


def test_the_link_validation_settings_are_what_makes_that_true(tmp_path: Path) -> None:
    """The anti-vacuity guard: prove the setting is load-bearing, not decorative.

    Same trap as `validation.nav.omitted_files`, which WP02 found: MkDocs defaults
    `anchors` to `info`, and `--strict` escalates only WARNING. So on the defaults, a
    link to an anchor that does not exist builds green — verified right here, so that
    nobody has to take the claim on trust, and so that a future "tidy-up" that drops the
    setting fails a test instead of quietly disabling FR-013 for the site.
    """
    defaults = tmp_path / "defaults"
    defaults.mkdir()
    on_defaults = _synthetic_project(
        defaults, "[anchor](index.md#not-a-real-anchor)\n", validation=None
    )
    _build_probe(on_defaults)  # exits cleanly — that is the point

    declared = _validation_declaration()
    assert declared["links"]["anchors"] == "warn"
    assert declared["links"]["unrecognized_links"] == "warn"
    assert declared["nav"]["omitted_files"] == "warn"


# --------------------------------------------------------------------------------------
# T012/T016 — the theme: bounded, contained at 320px, and readable in both schemes
# --------------------------------------------------------------------------------------

_OVERRIDES: Final[Path] = _REPO_ROOT / "src" / "theme" / "site" / "overrides"
_PALETTE: Final[Path] = _OVERRIDES / "stylesheets" / "palette.css"
_TYPOGRAPHY: Final[Path] = _OVERRIDES / "stylesheets" / "typography.css"

#: Foreground/background pairs that carry text, with the scheme-local custom properties
#: they are defined by. Every one must clear WCAG AA (4.5:1) in both schemes (NFR-006).
CONTRAST_PAIRS: Final[tuple[tuple[str, str, str], ...]] = (
    ("--md-typeset-color", "--md-default-bg-color", "body text"),
    ("--md-typeset-a-color", "--md-default-bg-color", "links"),
    ("--md-default-fg-color--light", "--md-default-bg-color", "captions and metadata"),
    ("--md-default-fg-color--light", "--md-code-bg-color", "the AI pointer"),
    ("--md-accent-fg-color", "--md-default-bg-color", "links on hover"),
    ("--md-code-fg-color", "--md-code-bg-color", "code"),
    ("--md-primary-bg-color", "--md-primary-fg-color", "the header"),
    ("--md-footer-fg-color", "--md-footer-bg-color", "the footer"),
)

_AA_NORMAL_TEXT: Final[float] = 4.5

_DECLARATION: Final[re.Pattern[str]] = re.compile(
    r"^\s*(--[\w-]+)\s*:\s*(#[0-9a-fA-F]{6})\s*;", re.MULTILINE
)


def _relative_luminance(hex_colour: str) -> float:
    """WCAG 2.1 relative luminance of an sRGB colour."""
    channels = [int(hex_colour[i : i + 2], 16) / 255 for i in (1, 3, 5)]
    linear = [c / 12.92 if c <= 0.03928 else ((c + 0.055) / 1.055) ** 2.4 for c in channels]
    return 0.2126 * linear[0] + 0.7152 * linear[1] + 0.0722 * linear[2]


def contrast_ratio(foreground: str, background: str) -> float:
    """The WCAG contrast ratio between two `#rrggbb` colours."""
    lighter, darker = sorted(
        (_relative_luminance(foreground), _relative_luminance(background)), reverse=True
    )
    return (lighter + 0.05) / (darker + 0.05)


def _scheme(css: str, name: str) -> dict[str, str]:
    """The custom properties declared for one Material colour scheme."""
    block = re.search(rf'\[data-md-color-scheme="{name}"\]\s*\{{(.*?)\n\}}', css, re.DOTALL)
    assert block is not None, f"palette.css declares no {name!r} scheme"
    return {m.group(1): m.group(2) for m in _DECLARATION.finditer(block.group(1))}


@pytest.mark.parametrize("scheme", ["default", "slate"])
def test_the_palette_meets_wcag_aa(scheme: str) -> None:
    """NFR-006, measured rather than trusted to the eye — in light AND dark.

    The dark scheme is where this usually goes wrong: a colour picked against white and
    then reused on near-black looks fine to whoever picked it and fails for everyone else.
    """
    colours = _scheme(_PALETTE.read_text(encoding="utf-8"), scheme)
    for foreground, background, what in CONTRAST_PAIRS:
        assert foreground in colours, f"{scheme} declares no {foreground}"
        assert background in colours, f"{scheme} declares no {background}"
        ratio = contrast_ratio(colours[foreground], colours[background])
        assert ratio >= _AA_NORMAL_TEXT, (
            f"{scheme}: {what} is {ratio:.2f}:1 ({colours[foreground]} on "
            f"{colours[background]}), below WCAG AA's {_AA_NORMAL_TEXT}:1"
        )


def test_both_schemes_are_offered(config: BuildConfig) -> None:
    """T012: the light/dark toggle, and each scheme bound to the reader's preference."""
    raw = yaml.safe_load(_MKDOCS_YML.read_text(encoding="utf-8").split("# --- The two theme")[0])
    palette = raw["theme"]["palette"]
    assert [entry["scheme"] for entry in palette] == ["default", "slate"]
    assert all("toggle" in entry and "media" in entry for entry in palette)


def test_the_palette_is_not_outranked_by_materials_own_colours() -> None:
    """The second measured-in-a-browser bug, and the one this file could not have caught.

    Left to default, Material stamps `data-md-color-primary="indigo"` on the body and
    ships

        [data-md-color-scheme=slate][data-md-color-primary=indigo]{--md-typeset-a-color:#5488e8}

    whose (0,2,0) specificity beats palette.css's `[data-md-color-scheme="slate"]` (0,1,0)
    regardless of load order. So the dark scheme's links rendered in Material's indigo
    while every contrast figure in this file was measured against ours — the tests were
    green and the site was not what they described.

    `primary: custom` is Material's own opt-out: it declares no rules for that value, so
    the palette is unopposed. Both halves are asserted, because the second is what makes
    the first true.
    """
    raw = yaml.safe_load(_MKDOCS_YML.read_text(encoding="utf-8").split("# --- The two theme")[0])
    for entry in raw["theme"]["palette"]:
        assert entry.get("primary") == "custom" and entry.get("accent") == "custom", (
            f"the {entry['scheme']!r} scheme does not set primary/accent to `custom`, so "
            "Material's own [scheme][primary] rules outrank palette.css and the rendered "
            "colours are not the ones this file measures"
        )

    assert "data-md-color-primary=custom" not in _material_stylesheet(), (
        "Material now ships rules for `primary: custom`, which may outrank palette.css. "
        "Re-check the rendered colours in a browser."
    )


def test_no_table_opts_out_of_materials_containment(site: Path) -> None:
    """A canary on Material's table containment. Not, on this content, the NFR-002 guard.

    Material contains a table with `.md-typeset table:not([class]) { max-width: 100%;
    overflow: auto }` — a CSS rule, not its JavaScript wrapper, so containment does not
    depend on a script running. The selector is the fragile part: a table that acquires a
    class (an `attr_list` annotation in the pack, say) silently falls out of that rule.
    That is what is asserted, on the real chapters.

    What this does *not* claim, having been measured rather than assumed: adding a class
    to `storytelling.md`'s tells table — the widest thing the guide has — does drop
    containment at 320px (`display` inline-block → table, `overflow-x` auto → hidden,
    `max-width` 100% → none) and the page still does not scroll sideways. The cells wrap
    into 286px. So on today's content it is `overflow-wrap: break-word` in typography.css
    doing the real work, and this test is an early warning that the containment mechanism
    has changed, not proof that NFR-002 holds.

    NFR-002 itself is verified by rendering all 13 pages at a 320px viewport and checking
    `scrollWidth == innerWidth`. Keep this canary — it fires before a genuinely wider
    table (one whose longest word exceeds the viewport) would — but do not read a green
    result here as the width guarantee. It is not one.
    """
    classed = []
    total = 0
    for path in site.rglob("index.html"):
        for match in re.finditer(r"<table([^>]*)>", path.read_text(encoding="utf-8")):
            total += 1
            if "class=" in match.group(1):
                classed.append(f"{path.relative_to(site)}: <table{match.group(1)}>")
    assert total, "sanity: the guide's chapters contain tables"
    assert not classed, (
        "these tables carry a class, so Material's containment rule "
        "`table:not([class])` no longer matches them and they will scroll the page at "
        "320px:\n" + "\n".join(classed)
    )


def test_the_widest_chapter_really_is_wide(site: Path) -> None:
    """Sanity for the test above: it is only worth anything against a wide table."""
    html = (site / "storytelling" / "index.html").read_text(encoding="utf-8")
    assert html.count("<th") >= 3, "storytelling.md's comparison table has lost its columns"


def test_our_css_does_not_undo_the_containment() -> None:
    """The other half: Material contains the tables unless we get in the way.

    The measure cap in typography.css applies to flow elements only, and deliberately not
    to tables — capping their container would narrow the scroll area for no benefit, and
    a `min-width` or a fixed `px` width on a table is the classic way a page starts
    scrolling sideways on a phone.
    """
    css = _without_comments(
        _TYPOGRAPHY.read_text(encoding="utf-8") + _PALETTE.read_text(encoding="utf-8")
    )
    for rule in re.finditer(r"([^{}]+)\{([^}]*)\}", css):
        selector, body = rule.group(1), rule.group(2)
        if "table" not in selector:
            continue
        assert "min-width" not in body, f"{selector.strip()} sets a min-width on a table"
        assert "overflow" not in body, f"{selector.strip()} overrides Material's containment"

    assert "max-width: 72ch" in css, "the measure cap has gone"
    assert not re.search(r"width:\s*\d{3,}px", css), "a fixed pixel width wider than a phone"


def _without_comments(css: str) -> str:
    """CSS with its comments removed, so a selector match cannot swallow the prose.

    These stylesheets are heavily commented on purpose; a rule-matching regex that does
    not strip comments first matches the comment above the rule.
    """
    return re.sub(r"/\*.*?\*/", "", css, flags=re.DOTALL)


def _material_stylesheet() -> str:
    """Material's own compiled CSS — the thing our overrides have to win against.

    Every sheet, not just `main.*.min.css`. The two signals this file reads off Material
    live in different files: `--md-text-font-family` is declared in `main`, while all 50
    occurrences of `data-md-color-primary` — including the
    `[scheme][primary=indigo]{--md-typeset-a-color:#5488e8}` rule that `primary: custom`
    exists to escape — are in the sibling `palette.*.min.css`. Globbing `main` alone
    pointed the palette canary at a file that could never carry its signal, so it could
    not fail. Concatenating is what gives it teeth.
    """
    spec = importlib.util.find_spec("material")
    assert spec is not None and spec.origin is not None, "Material is not installed"
    sheets = sorted(
        (Path(spec.origin).parent / "templates" / "assets" / "stylesheets").glob("*.min.css")
    )
    assert sheets, "Material's stylesheets are not where they have always been"
    return "".join(sheet.read_text(encoding="utf-8") for sheet in sheets)


def test_the_font_stack_is_declared_where_material_can_see_it() -> None:
    """The silent no-op that shipped a font nobody chose, pinned down.

    Material declares `--md-text-font-family` **on `body`**, not on `:root`. So a
    `:root { --md-text-font-family: ... }` override sets the variable on `html` and is
    then shadowed at `body` by Material's own declaration: every element resolves
    Material's, the `var(--md-text-font, _)` fallback kicks in, and the site renders in
    the system sans-serif. Nothing warns. `getComputedStyle(html)` even reports our value
    back, because on `html` it genuinely is set — which is what makes this so easy to
    "verify" and still get wrong. It was caught by measuring a rendered page.

    Two things are asserted, and the second is the one with a shelf life:
      1. our declaration sits on `body`, at the same specificity, in a stylesheet that
         loads after Material's;
      2. Material still declares it on `body`. If a Material upgrade moves that
         declaration, this fails — and the fix is to re-check the rendered page, not to
         edit the assertion.
    """
    material_css = _material_stylesheet()
    declaring = re.search(r"([^{};]*)\{[^{}]*--md-text-font-family:", material_css)
    assert declaring is not None, "Material no longer declares --md-text-font-family at all"
    assert declaring.group(1).strip().endswith("body"), (
        f"Material now declares --md-text-font-family on {declaring.group(1)!r}, not on "
        "`body`. Our override in typography.css targets `body` precisely to beat it — "
        "re-check the rendered page's computed font-family before adjusting this."
    )

    ours = re.search(
        r"([^{}]*)\{([^{}]*--md-text-font-family:[^{}]*)\}",
        _without_comments(_TYPOGRAPHY.read_text(encoding="utf-8")),
    )
    assert ours is not None, "typography.css declares no font stack"
    assert ours.group(1).strip() == "body", (
        f"the font stack is declared on {ours.group(1).strip()!r}. Material declares it "
        "on `body`, which shadows anything set on `:root` — the site would silently "
        "render in the system sans-serif."
    )
    assert "--md-code-font-family" in ours.group(2), "the mono stack shares the same trap"


def test_the_theme_is_not_silently_git_ignored() -> None:
    """The third trap of this kind, and the one that would have shipped nothing at all.

    `.gitignore` carried an unanchored `site/` for the MkDocs output — which also matches
    `src/theme/site/`, this work package's whole authoritative surface. Git declines to
    add it and says nothing; the palette, the typography and the template override simply
    never leave the machine, and the build fails later and elsewhere, on a `custom_dir`
    that is not there. The pattern is now anchored to the repo root (`/site/`).

    `--no-index` is load-bearing, and its absence was this guard's own version of the bug
    it guards. `git check-ignore` consults the index by default and reports nothing for a
    tracked file — so once the theme was committed, the check passed no matter what the
    pattern said, and reverting `.gitignore` to the unanchored `site/` left it green.
    `--no-index` asks the question actually at stake: would the pattern refuse a *new*
    file here? That is the live failure — `src/theme/site/overrides/partials/foo.html`
    added tomorrow is still silently unaddable under an unanchored `site/`, and the
    existing files being tracked does nothing to save the next contributor.
    """
    tracked = [
        str(path.relative_to(_REPO_ROOT))
        for path in (_REPO_ROOT / "src" / "theme").rglob("*")
        if path.is_file()
    ]
    assert tracked, "sanity: the theme has files"

    ignored = subprocess.run(
        ["git", "check-ignore", "--no-index", *tracked],
        cwd=_REPO_ROOT,
        capture_output=True,
        text=True,
        check=False,
    )
    assert not ignored.stdout.strip(), (
        "git ignores part of the theme, so it cannot be committed and the site will "
        f"build without it:\n{ignored.stdout}"
    )


def test_the_theme_ships_through_custom_dir_and_not_into_the_product(config: BuildConfig) -> None:
    """C-002/C-006, and the trap WP02 documented in mkdocs.yml.

    `extra_css` resolves against `docs_dir` — which is `src/pack/`, the product — and it
    fails silently: MkDocs exits 0 and ships a `<link>` to a 404. The role lint would not
    catch the stray asset either, because it globs `*.md`. So both halves are asserted
    here: the config does not declare `extra_css`, and no build asset has appeared in the
    pack.
    """
    raw = yaml.safe_load(_MKDOCS_YML.read_text(encoding="utf-8").split("# --- The two theme")[0])
    assert "extra_css" not in raw, (
        "mkdocs.yml declares extra_css. Its paths resolve against docs_dir (src/pack/), "
        "so the stylesheet would have to be written into the guide (C-002, C-006) — and "
        "if it is not, MkDocs exits 0 and serves a silent 404. Ship CSS via custom_dir."
    )
    assert raw["theme"]["custom_dir"] == "src/theme/site/overrides"

    strays = [p.name for p in config.pack_dir.rglob("*") if p.is_file() and p.suffix != ".md"]
    assert not strays, f"build assets have been written into the product: {strays}"


def test_the_stylesheets_reach_the_output(site: Path) -> None:
    """The silent-404 half, asserted on the built site rather than on the config."""
    for name in ("palette.css", "typography.css"):
        assert (site / "stylesheets" / name).is_file()

    html = (site / "ethics" / "index.html").read_text(encoding="utf-8")
    for name in ("palette.css", "typography.css"):
        assert re.search(
            rf'<link rel="stylesheet" href="[^"]*stylesheets/{name}">', html
        ), f"{name} is in the output but no page links it"


def test_the_theme_is_material_lightly_dressed() -> None:
    """NFR-004/A-004: palette and typography only. The budget, as a test.

    Not a matter of taste: a bespoke identity was weighed and ruled Out of Scope. One
    template override exists, and it is there for FR-002's pointer and to link the CSS —
    not to redesign anything. If this fires, the question to ask is whether the addition
    is a requirement or a project.
    """
    templates = sorted(p.name for p in _OVERRIDES.rglob("*.html"))
    assert templates == ["main.html"], (
        f"the theme has grown template overrides beyond main.html: {templates}. A "
        "distinctive identity for the guide is Out of Scope (A-004); raise it rather "
        "than building it."
    )

    stylesheets = sorted(p.name for p in _OVERRIDES.rglob("*.css"))
    assert stylesheets == ["palette.css", "typography.css"]

    assert not list(
        _OVERRIDES.rglob("*.js")
    ), "the theme has grown JavaScript. Material's own behaviour is the budget (NFR-004)."


def test_the_build_fails_loudly_on_a_pack_it_cannot_derive_from(
    tmp_path: Path, caplog: pytest.LogCaptureFixture
) -> None:
    """The hook's failures are build failures, not warnings.

    T013's rule, applied to the whole hook: a landing page that cannot be derived, a
    document with no declared role, a base that is not a base. Each is a `PluginError`,
    which MkDocs turns into a failed build with the message intact.
    """
    docs = tmp_path / "src" / "pack"
    docs.mkdir(parents=True)
    (docs / "creator-kit.md").write_text("# Kit\n\nNo pitch in here.\n", encoding="utf-8")

    config_path = tmp_path / "mkdocs.yml"
    config_path.write_text(
        yaml.safe_dump(
            {
                "site_name": "Probe",
                "site_url": "https://example.test/probe/",
                "docs_dir": "src/pack",
                "site_dir": str(tmp_path / "site"),
                "nav": [{"Creator Kit": "creator-kit.md"}],
                "hooks": [str(_REPO_ROOT / "src" / "build" / "site.py")],
            },
            sort_keys=False,
        ),
        encoding="utf-8",
    )

    # A PluginError is a BuildError, which MkDocs logs and turns into an aborted build
    # with the message intact — a failure a human can act on, not an empty page.
    with pytest.raises(Abort):
        mkdocs_build(mkdocs_load_config(config_file=str(config_path), strict=True))
    assert PITCH_MARKER in caplog.text
    assert "FR-001" in caplog.text


def test_the_published_book_is_traceable(site: Path, config: BuildConfig) -> None:
    """NFR-003 over this work package's own output, via WP02's checker.

    The site is the surface with the most files, so it is the one where a hand-authored
    page would hide most easily.
    """
    from build.provenance import verify_provenance

    verify_provenance(site, config)
